### ISSUE TITLE
Il registro crasha all'avvio 

### ISSUE THREAD

**Issue by NikkoSanna** [Giua-app/Giua-App#62]
Build version: 0.5.40-manual-build 
Build date: 1981-01-01 01:01:02 
Current date: 2021-10-17 07:44:16 
Device: HUAWEI ANE-LX1 
OS version: Android 9 (SDK 28) 
 
Stack trace:  
com.giua.webscraper.GiuaScraperExceptions$UnableToLogin: Unable to login: Login unsuccessful, and the site didn't give an error message. Please check the site from your web browser
	at com.giua.webscraper.GiuaScraper.login(GiuaScraper.java:1809)
	at com.giua.app.ui.activities.AutomaticLoginActivity.lambda$loginWithPreviousCredentials$10$AutomaticLoginActivity(AutomaticLoginActivity.java:75)
	at com.giua.app.ui.activities.AutomaticLoginActivity$$ExternalSyntheticLambda9.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:784)

User actions: 
2021-10-17 07:44:06: AutomaticLoginActivity created
2021-10-17 07:44:06: AutomaticLoginActivity resumed
2021-10-17 07:44:07: ActivityManager destroyed

**Comment by NikkoSanna** [comment]
Penso che il crash sia dovuto alla dark mode, attivandola crasha istantaneamente

**Comment by Franck1421** [comment]
Siamo a conoscenza di questo errore. È dovuto al fatto che la schermata di login iniziale del sito del registro è cambiata
