### ISSUE TITLE
L'app crasha cercando di aprire una Attività nell'Agenda

### ISSUE THREAD

**Issue by NikkoSanna** [Giua-app/Giua-App#75]
Build version: 0.6.1-stable 
Build date: 17-11-2021 19:31:55 
Current date: 23-11-2021 07:56:33 
Device: HUAWEI ANE-LX1 
OS version: Android 9 (SDK 28) 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at java.util.Vector.get(Vector.java:748)
	at com.giua.app.ui.fragments.agenda.AgendaFragment.lambda$agendaViewOnClick$10$com-giua-app-ui-fragments-agenda-AgendaFragment(AgendaFragment.java:383)
	at com.giua.app.ui.fragments.agenda.AgendaFragment$$ExternalSyntheticLambda10.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

User actions: 
2021-11-23 07:55:30: AutomaticLoginActivity created
2021-11-23 07:55:30: AutomaticLoginActivity resumed
2021-11-23 07:55:30: ActivityManager destroyed
2021-11-23 07:55:30: AutomaticLoginActivity paused
2021-11-23 07:55:30: DrawerActivity created
2021-11-23 07:55:30: DrawerActivity resumed
2021-11-23 07:55:31: AutomaticLoginActivity destroyed

**Comment by HiemSword** [comment]
Non riesco a riprodurre il bug, puoi mandare uno screenshot dei log? Puoi accedere ai log dalle impostazioni nella sezione debug
![IMG_20211123_100804.jpg](https://user-images.githubusercontent.com/34164621/142997612-6841446c-0311-4b2c-bb90-114773ddc78b.jpg) e fai lo screenshot dalla scritta ERROR 
![IMG_20211123_103256](https://user-images.githubusercontent.com/34164621/143000471-4ee5ef22-e23c-4bcc-837d-7fe9bd77f479.jpg)
fino alla scritta dell'inizio della sessione
![IMG_20211123_103246](https://user-images.githubusercontent.com/34164621/143000657-ea9bafd6-da3f-4501-b159-129c5bd2434f.jpg)

**Comment by NikkoSanna** [comment]
Build version: 0.6.1-stable 
Build date: 17-11-2021 19:31:55 
Current date: 25-11-2021 07:29:37 
Device: HUAWEI ANE-LX1 
OS version: Android 9 (SDK 28) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.giua.app/com.giua.app.ui.activities.LogdogViewerActivity}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.giua.utils.LoggerManager.parseLogsFrom(LoggerManager.java:94)
	at com.giua.app.ui.activities.LogdogViewerActivity.onCreate(LogdogViewerActivity.java:69)
	at android.app.Activity.performCreate(Activity.java:7458)
	at android.app.Activity.performCreate(Activity.java:7448)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
	... 11 more

User actions: 
2021-11-25 07:29:04: AutomaticLoginActivity created
2021-11-25 07:29:04: AutomaticLoginActivity resumed
2021-11-25 07:29:04: AutomaticLoginActivity paused
2021-11-25 07:29:04: DrawerActivity created
2021-11-25 07:29:04: DrawerActivity resumed
2021-11-25 07:29:05: AutomaticLoginActivity destroyed
2021-11-25 07:29:05: ActivityManager destroyed
2021-11-25 07:29:08: DrawerActivity paused
2021-11-25 07:29:08: SettingsActivity created
2021-11-25 07:29:08: SettingsActivity resumed
2021-11-25 07:29:11: SettingsActivity paused
2021-11-25 07:29:11: ActivityManager created
2021-11-25 07:29:11: AutomaticLoginActivity created
2021-11-25 07:29:11: AutomaticLoginActivity resumed
2021-11-25 07:29:11: ActivityManager destroyed
2021-11-25 07:29:20: AutomaticLoginActivity paused
2021-11-25 07:29:20: StudentLoginActivity created
2021-11-25 07:29:20: StudentLoginActivity resumed
2021-11-25 07:29:21: AutomaticLoginActivity destroyed
2021-11-25 07:29:23: StudentLoginActivity paused
2021-11-25 07:29:23: DrawerActivity created
2021-11-25 07:29:24: DrawerActivity resumed
2021-11-25 07:29:28: DrawerActivity paused
2021-11-25 07:29:28: SettingsActivity created
2021-11-25 07:29:28: SettingsActivity resumed
2021-11-25 07:29:30: SettingsActivity paused
2021-11-25 07:29:30: LogdogViewerActivity created

crasha...

**Comment by HiemSword** [comment]
Ma crasha ogni volta che provi ad usare il logdog? Di solito questo crash si verifica quando non c'è nessun log/messaggio presente in memoria (è gia in programma un fix).
Se crasha sempre a questo punto fai prima a disinstallare e reinstallare l'app, sperando si sistemi pure il crash dell'agenda

**Comment by HiemSword** [comment]
In goni caso, il crash dovrebbe essere stato fixato in a6fe8fc90b7367571ccd6f85f987846ec03d8957

**Comment by HiemSword** [comment]
Abbiamo capito perchè crashava, non abbiamo ancora aggiunto il supporto per le "Attività" nell'Agenda e quindi crasha visto che non sa come gestirle. Rilascieremo tra qualche giorno la nuova versione con incluso il fix

**Comment by NikkoSanna** [comment]
> Abbiamo capito perchè crashava, non abbiamo ancora aggiunto il supporto per le "Attività" nell'Agenda e quindi crasha visto che non sa come gestirle. Rilascieremo tra qualche giorno la nuova versione con incluso il fix

Ok

**Comment by Franck1421** [comment]
Risolto completamente in https://github.com/Giua-app/Giua-App/commit/6a1f4a2c7a29713fc4bd34e86b469d04643a6059
